# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Index_Form_GF.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        Form.setMinimumSize(QtCore.QSize(400, 300))
        Form.setMaximumSize(QtCore.QSize(400, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Earth.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.Input_Edit = QtWidgets.QLineEdit(Form)
        self.Input_Edit.setEnabled(True)
        self.Input_Edit.setObjectName("Input_Edit")
        self.horizontalLayout.addWidget(self.Input_Edit)
        self.Open_Button = QtWidgets.QPushButton(Form)
        self.Open_Button.setObjectName("Open_Button")
        self.horizontalLayout.addWidget(self.Open_Button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.Output_Edit = QtWidgets.QLineEdit(Form)
        self.Output_Edit.setObjectName("Output_Edit")
        self.horizontalLayout_2.addWidget(self.Output_Edit)
        self.Save_Button = QtWidgets.QPushButton(Form)
        self.Save_Button.setObjectName("Save_Button")
        self.horizontalLayout_2.addWidget(self.Save_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.Cal_Button = QtWidgets.QPushButton(Form)
        self.Cal_Button.setObjectName("Cal_Button")
        self.horizontalLayout_3.addWidget(self.Cal_Button)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)

        self.retranslateUi(Form)
        self.Open_Button.clicked.connect(Form.Open_img)
        self.Save_Button.clicked.connect(Form.Save_img)
        self.Cal_Button.clicked.connect(Form.Cal_index)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "遥感指数计算GF"))
        self.label.setText(_translate("Form", "请选择遥感影像："))
        self.Open_Button.setText(_translate("Form", "…"))
        self.label_2.setText(_translate("Form", "请选择保存路径："))
        self.Save_Button.setText(_translate("Form", "…"))
        self.Cal_Button.setText(_translate("Form", "计算"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:10pt;\">本模块利用GF遥感影像计算植被指数（NDVI）和水体指数（NDWI）。</span></p><p><span style=\" font-size:10pt;\">1、选择多波段遥感影像（TIF格式，DAT格式）；</span></p><p><span style=\" font-size:10pt;\">2、设置指数保存路径；</span></p><p><span style=\" font-size:10pt;\">3、计算。</span></p></body></html>"))
